name: create-dist
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

env:
  LOVE_VERSION: "11.5"

jobs:
  create-love-file:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Make create_archive.sh executable
        run: chmod +x ./create_archive.sh
      - name: create game archive
        run: ./create_archive.sh
      - name: upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: LDJAM56.love
          path: ./LDJAM56.love

  create-windows-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - name: download required windows files
        run: curl -sSL https://github.com/love2d/love/releases/download/${LOVE_VERSION}/love-${LOVE_VERSION}-win64.zip -o ./love-${LOVE_VERSION}-win64.zip
      - name: extract required windows files
        run: unzip ./love-${LOVE_VERSION}-win64.zip
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: LDJAM56.love
          path: ./
      - name: create windows release
        run: |
          cp -r ./love-${LOVE_VERSION}-win64/ ./dist/
          cat ./dist/love.exe ./LDJAM56.love > ./dist/LDJAM56.exe
          rm ./dist/love.exe
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win64
          path: ./dist

  create-linux-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - name: install appimagetool
        run: |
          sudo apt update
          sudo apt install -y fuse
          curl -sSL https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage -o /usr/local/bin/appimagetool
          chmod +x /usr/local/bin/appimagetool
      - name: download required linux file
        run: |
          curl -sSL https://github.com/love2d/love/releases/download/${LOVE_VERSION}/love-${LOVE_VERSION}-x86_64.AppImage -o ./love.AppImage
          chmod +x ./love.AppImage
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: LDJAM56.love
          path: ./
      - name: create linux release
        run: |
          mkdir dist
          ./love.AppImage --appimage-extract
          cp ./LDJAM56.love ./squashfs-root/LDJAM56.love
          sed -i '/# uncomment and edit to add your own game/ a FUSE_PATH=$APPDIR/LDJAM56.love' squashfs-root/AppRun
          appimagetool ./squashfs-root ./LDJAM56.AppImage
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./LDJAM56.AppImage

  create-mac-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - uses: actions/checkout@v4
      - name: download required mac file
        run: |
          curl -sSL https://github.com/love2d/love/releases/download/11.5/love-11.5-macos.zip -o ./love.zip
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: LDJAM56.love
          path: ./
      - name: create mac release
        run: |
          unzip love.zip
          mv love.app LDJAM56.app
          mv LDJAM56.love LDJAM56.app/Contents/Resources/
          sed -i 's/<string>org\.love2d\.love<\/string>/<string>com.ldjam.LDJAM56<\/string>/' ./LDJAM56.app/Contents/Info.plist
          sed -i 's/<string>LÖVE<\/string>/<string>LDJAM56<\/string>/' ./LDJAM56.app/Contents/Info.plist
          sed -i 's/OS X AppIcon/homunculus/' ./LDJAM56.app/Contents/Info.plist
          sed -i '106,+28 d' ./LDJAM56.app/Contents/Info.plist
          cp press_material/homunculus.icns ./LDJAM56.app/Contents/Resources/homunculus.icns
          zip -yr LDJAM56_macos.zip ./LDJAM56.app

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: ./LDJAM56_macos.zip


  create-web-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - name: install love.js
        run: npm -g install love.js
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: LDJAM56.love
          path: ./
      - name: create web release
        run: |
          love.js --compatibility --title "LDJAM56" ./LDJAM56.love ./dist/
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./dist