name: release
on:
  release:
    types: [ "published", "created " ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  create-artifacts:
    uses: ./.github/workflows/create_dist.yml

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [ create-artifacts ]
    steps:
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: LDJAM56.love
          path: ./
      - name: download windows files
        uses: actions/download-artifact@v4
        with:
          name: win64
          path: ./LDJAM56-win64
      - name: package windows files
        run: zip -r ./LDJAM56-win64.zip ./LDJAM56-win64
      - name: download linux files
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: ./
      - name: download mac files
        uses: actions/download-artifact@v4
        with:
          name: mac
          path: ./
      - name: rename mac file
        run: mv ./LDJAM56.zip ./LDJAM56-macos.zip
      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./LDJAM56.love
            ./LDJAM56-win64.zip
            ./LDJAM56-macos.zip
            ./LDJAM56.AppImage

  deploy-github-pages:
    runs-on: ubuntu-latest
    needs: [ create-artifacts ]
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: download web files
        uses: actions/download-artifact@v4
        with:
          name: web
          path: ./web
      - name: upload github pages artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web
      - name: deploy new pages version
        id: deploy-pages
        uses: actions/deploy-pages@v4